PB-1: Добавил описание правил работы с git и assets
IT-manager-playbook/playbook pull request #7
Opened 2023-11-16 17:29 UTC by roberqwerty

2023-11-17 09:28 UTC, fduch2k requested changes

2023-11-17 09:28 UTC, fduch2k commented on rules/ASSETS.MD
> +1. Ссылки
Элементы списка равнозначны и ссылок на них нет - можно использовать неупорядоченный список
```suggestion
* Книги,
* Видео,
* Прочее.
```

2023-11-17 09:28 UTC, fduch2k commented on rules/ASSETS.MD
> +Ссылки храняться в отдельном MD файле: LINKS.MD
```suggestion
### Прочее
Все что не попадает под категории "Книги" и "Видео". Хранится в отдельном файле `LINKS.MD`
```

2023-11-17 09:28 UTC, fduch2k commented on rules/ASSETS.MD
> +Ценность
```suggestion
Описание ценности, желательно не больше 140 символов.
```

2023-11-17 09:28 UTC, fduch2k commented on rules/GIT_RULES.MD
> +1. Перевести задачу в статус `Done`
Необходимо поправить нумерацию в списке.

2023-11-17 09:28 UTC, fduch2k commented on rules/GIT_RULES.MD
> +- Комментарии при коммитах в своей ветке круче делать так: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`, основная ценность в том, чтобы в случае слияния нескольких ветко в одну - было проще разобрать
Лучше добавить пример - будет нагляднее

2023-11-17 09:34 UTC, fduch2k commented on rules/GIT_RULES.MD
> +1. Создать новую ветку по принципу: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`
```suggestion
1. Создать новую ветку по принципу: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`
1. В задаче указать Project и Milestone на который запланирован выполнение;
```

2023-11-17 14:27 UTC, fduch2k commented on rules/GIT_RULES.MD
> +- Комментарии при коммитах в своей ветке круче делать так: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`, основная ценность в том, чтобы в случае слияния нескольких ветко в одну - было проще разобрать
А точно нужен `PROJECT_PREFIX`? Если будет что-то совсем стороннее - лучше отдельный реп сделать.

2023-11-17 15:40 UTC, roberqwerty commented on rules/GIT_RULES.MD
> +1. Перевести задачу в статус `Done`
Это MD файл, он в результате становиться в правильном порядке.

2023-11-19 08:52 UTC, roberqwerty commented on rules/GIT_RULES.MD
> +- Комментарии при коммитах в своей ветке круче делать так: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`, основная ценность в том, чтобы в случае слияния нескольких ветко в одну - было проще разобрать
Добавил пример

2023-11-19 08:55 UTC, roberqwerty commented on rules/GIT_RULES.MD
> +1. Создать новую ветку по принципу: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`
Вот тут нужно обсуждать: исполнение задачи и ее постановка - это разные процесс как минимум, потому что есть DoR и DoD. Правила работы с git предполагают наличие заведенной задачи, кстати для этого сделал вот эту задачу: https://github.com/IT-manager-playbook/playbook/issues/9

2023-11-19 08:56 UTC, roberqwerty commented on rules/GIT_RULES.MD
> +- Комментарии при коммитах в своей ветке круче делать так: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`, основная ценность в том, чтобы в случае слияния нескольких ветко в одну - было проще разобрать
Смотри `PROJECT_PREFIX` как раз дает понимание, о каком проекте идет речь, для чего-то стороннего скорее всего будет отдельный проект и отдельный репозиторий.

2023-11-19 10:03 UTC, fduch2k commented on rules/GIT_RULES.MD
> +- Комментарии при коммитах в своей ветке круче делать так: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`, основная ценность в том, чтобы в случае слияния нескольких ветко в одну - было проще разобрать
Давай обсудим на звонке - мне кажется все таки излишне, может у тебя другое видение структуры проектов и репов, надо засинхронизировать

2023-11-19 10:06 UTC, fduch2k commented on rules/GIT_RULES.MD
> +1. Создать новую ветку по принципу: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`
Я так понимаю это правила для конкретного репозитория, как все будем оформлять именно в нашем проекте. А задача #9  - это про общие принципы написания и валидации задачи - это можно только как справочное добавить, но там не будет конкретики про поля в Jira или GitHub  как и чем их заполнять. Надо это как то разделить

2023-11-20 14:35 UTC, roberqwerty commented on rules/GIT_RULES.MD
> +1. Создать новую ветку по принципу: `{PROJECT_PREFIX}_{TASK_ID}_{SHORT_COMMENT}`
Не применяем строчку сейчас, но выносим ее в отдельный документ в будущем (в #9 ).

2023-11-20 14:38 UTC, fduch2k approved these changes

2023-11-20 14:38 UTC, merged